add join table for visits
mosidrum/vet_clinic pull request #5
Opened 2023-08-17 16:36 UTC by mosidrum

add join table for visits and queried data to answer some questions

![16](https://github.com/mosidrum/vet_clinic/assets/97716175/cb1c221f-eea3-4795-96ab-f5af770cb0f5)
![17](https://github.com/mosidrum/vet_clinic/assets/97716175/424bd323-13ec-46a8-8d3f-c9452b0d9f6b)
![18](https://github.com/mosidrum/vet_clinic/assets/97716175/c71af9da-29e6-4872-9d64-3b079060bdda)
![19](https://github.com/mosidrum/vet_clinic/assets/97716175/80768b2f-4c8e-4e38-bfb2-ae628dfb8e2d)
![20](https://github.com/mosidrum/vet_clinic/assets/97716175/0f6fc3cc-f211-4a8f-80bb-2de6543e7bad)
![21](https://github.com/mosidrum/vet_clinic/assets/97716175/9f59a296-5e11-4c03-b9c0-356c3050d4b9)
![22](https://github.com/mosidrum/vet_clinic/assets/97716175/0fc54dcf-094e-48a7-85c5-33c2723b2450)
![23](https://github.com/mosidrum/vet_clinic/assets/97716175/d0bff6fb-f11d-49e6-8d1c-23eadc5d96d4)
![15](https://github.com/mosidrum/vet_clinic/assets/97716175/cea97ce6-03bc-4632-b2ca-ee528c8b84da)

2023-08-17 18:56 UTC, LionRouge1 requested changes
Hi @mosidrum, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good job using `JOIN` for many-to-many relationships :1st_place_medal: 
- Nice work providing SQL queries to answer the questions :+1: 
- Add the queries' result screenshots to PR :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 18:56 UTC, LionRouge1 commented on queries.sql
> +  (SELECT id FROM species WHERE name = 'Digimon'));
- [ ] Please note that for this question (**What specialty should Maisy Smith consider getting? Look for the species she gets the most.**), we are looking for the species that **Maisy Smith** get the most not the number of times she gets 'Digimon'. With that in mind, I think your query could look like this :point_down: 
```sql
  SELECT species.name, count(*)
  FROM visits
  LEFT JOIN animals ON animals.id = visits.animal_id
  LEFT JOIN species ON animals.species_id = species.id
  LEFT JOIN vets ON vets.id = visits.vet_id
  WHERE vet.name = 'Maisy Smith'
  GROUP BY species.name
```

2023-08-17 20:44 UTC, mosidrum commented
![24](https://github.com/mosidrum/vet_clinic/assets/97716175/864fe10f-44e0-4d42-9fc7-1141f5ae796a)

2023-08-18 02:32 UTC, Owusu-Desmond approved these changes
Hi @mosidrum , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/pCO5tKdP22RC8/giphy.gif"/>

## Highlights
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 03:37 UTC, merged